# Generated by Django 3.0.3 on 2021-01-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('mobail', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
            ],
        ),
    ]
