# Generated by Django 3.0.3 on 2021-01-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_rgistration', '0002_auto_20210121_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobail',
            field=models.IntegerField(),
        ),
    ]
